#!/bin/sh
if [ "$#" = 4 ]
then
  path=blog/$1/$2/$3
  title=$4
elif [ "$#" = 1 ]
then
  path=blog/$(date "+%Y/%m/%d")
  title=$1
else
  echo "USAGE: $0 year month day title"
  exit 1
fi

mkdir -p "$path"
touch "$path/$title.md"
nvim "$path/$title.md"
